version: '2'
services:
  spiralexpress-postgresql:
    image: postgres:12.3
    #    volumes:
    #      - ../../../../volumes/jhipster/spiralExpress/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=spiralExpress
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - spiralexpress-postgresql
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spiral.com
      PGADMIN_DEFAULT_PASSWORD: admin
