
export enum Pays {
    CAMEROUN = "CAMEROUN",
    RWANDA = "RWANDA",
    CONGO_BRAZZAVILLE = "CONGO_BRAZZAVILLE",
    BURKINA_FASO = "BURKINA_FASO",
    BELGIQUE = "BELGIQUE",
    LUXEMBOURG = "LUXEMBOURG",
    FRANCE = "FRANCE",
    ALLEMAGNE = "ALLEMAGNE"

}
