# ===================================================================
# Spring Boot configuration.
# ===================================================================
spring:
  profiles:
    active: dev
  application:
    name: spiralExpress

server:
  servlet:
    session:
      cookie:
        http-only: true

# application:
