# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    com.spiral.express: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/spiralExpress
    username: spiralExpress
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernates:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: gyleentrepreneur@gmail.com
    password: entrepreneur1989
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard

server:
  port: 8080

application:
  twilio:
    account-sid: AC76125ec69b9076d4d65427cefe5c4346
    auth-token: 75599ca2fe260e0adef42aa5388cedad
    phone-number: '+13518881502'
  mail:
    from: gyleentrepreneur@gmail.com
  sendSms: false
